sudo: required
language: node_js
node_js:
  - "7"
branches:
  only:
    - master
before_install:
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN